name: Run Pokémon Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pokemon-scraper .

      - name: Run scraper
        run: docker run --rm -v "$(pwd)/data:/app/data" pokemon-scraper

      - name: Upload data
        uses: actions/upload-artifact@v3
        with:
          name: pokemon-card-prices
          path: data/
